[[main]]
    name = "About Us"
    weight = 20
    url = "/about_us"
[[main]]
    parent = "About Us"
    name = "Our Mission"
    weight = 21
    url = "/about_us/ourmission/"    
[[main]]
    parent = "About Us"
    name = "Our team 2024-25"
    weight = 22
    url = "/about_us/ourteam/"    
[[main]]
    parent = "About Us"
    name = "Past members"
    weight = 23 
    url = "/about_us/pastmembers/"    
[[main]]
    parent = "About Us"
    name = "OHBM Code of Conduct"
    weight = 24 
    url = "https://www.humanbrainmapping.org/i4a/pages/index.cfm?pageid=3912"    
[[main]]
    name = "Symposia"
    weight = 30
    url = "/symposia/"
[[main]]
    name = "Roundtable"
    weight = 40
    url = "/roundtable/"
[[main]]
    name = "Brain Mappers of Tomorrow"
    weight = 50   
    url = "/kidsreview" 
[[main]]
    parent = "Brain Mappers of Tomorrow"
    name = "2021"
    weight = 55
    url = "https://youtube.com/playlist?list=PLocwiMktiT-6qUcqfP1qronR16EHLW3NM"
[[main]]
    parent = "Brain Mappers of Tomorrow"
    name = "2022"
    weight = 54
    url = "https://youtube.com/playlist?list=PLocwiMktiT-5w99sH6XGSWwsMyj2TMlm_"
[[main]]
    parent = "Brain Mappers of Tomorrow"
    name = "2023"
    weight = 53
    url = "/kidsreview/2023/"
[[main]]
    parent = "Brain Mappers of Tomorrow"
    name = "2024"
    weight = 52
    url = "/kidsreview/2024/"
[[main]]
    parent = "Brain Mappers of Tomorrow"
    name = "2025"
    weight = 51
    url = "/kidsreview/2025/"
[[main]]
    name = "Posts"
    weight = 60 
    url = "/posts/"
[[main]]
    name = "Publications"
    weight = 70
    url = "/publications/"
[[main]]
    name = "Links"
    weight = 80  
    url = "/links/"
[[main]]
    name = "Contact Us"
    weight = 90   
    url = "/contactus/"
    
